---
title: "Lodes OD Accquistion"
author: "Owen Hart"
date: "7/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Loading in libraries
```{r}
library(R.utils)
library(data.table)
library(tidyr)
library(dplyr)
#devtools::install_git("https://github.com/hrbrmstr/lodes.git")
library(lodes)
```

Downloading main lodes od
```{r}
#2017
download.file(
  url = "https://lehd.ces.census.gov/data/lodes/LODES7/or/od/or_od_main_JT00_2017.csv.gz", 
  destfile = "../data/LODES/or_od_main_JT00_2017.csv.gz")

gunzip("../data/LODES/or_od_main_JT00_2017.csv.gz")

#2016
download.file(
  url = "https://lehd.ces.census.gov/data/lodes/LODES7/or/od/or_od_main_JT00_2016.csv.gz", 
  destfile = "../data/LODES/or_od_main_JT00_2016.csv.gz")

gunzip("../data/LODES/or_od_main_JT00_2016.csv.gz")

#2015
download.file(
  url = "https://lehd.ces.census.gov/data/lodes/LODES7/or/od/or_od_main_JT00_2015.csv.gz", 
  destfile = "../data/LODES/or_od_main_JT00_2015.csv.gz")

gunzip("../data/LODES/or_od_main_JT00_2015.csv.gz")
```

Downloading aux lodes od
```{r}
download.file(
  url = "https://lehd.ces.census.gov/data/lodes/LODES7/or/od/or_od_aux_JT00_2017.csv.gz", 
  destfile = "../data/LODES/or_od_aux_JT00_2017.csv.gz")

gunzip("../data/LODES/or_od_aux_JT00_2017.csv.gz")


download.file(
  url = "https://lehd.ces.census.gov/data/lodes/LODES7/or/od/or_od_aux_JT00_2016.csv.gz", 
  destfile = "../data/LODES/or_od_aux_JT00_2016.csv.gz")

gunzip("../data/LODES/or_od_aux_JT00_2016.csv.gz")


download.file(
  url = "https://lehd.ces.census.gov/data/lodes/LODES7/or/od/or_od_aux_JT00_2016.csv.gz", 
  destfile = "../data/LODES/or_od_aux_JT00_2016.csv.gz")

gunzip("../data/LODES/or_od_aux_JT00_2016.csv.gz")
```

Reading in files
```{r}
main17 <- fread("../data/LODES/or_od_main_JT00_2017.csv", 
              colClasses = c("w_geocode" = "character",
                             "h_geocode" = "character"))

aux17 <- fread("../data/LODES/or_od_aux_JT00_2017.csv", 
              colClasses = c("w_geocode" = "character",
                             "h_geocode" = "character"))

full_data17 <- rbind(main, aux)


main16 <- fread("../data/LODES/or_od_main_JT00_2016.csv", 
              colClasses = c("w_geocode" = "character",
                             "h_geocode" = "character"))

aux16 <- fread("../data/LODES/or_od_aux_JT00_2016.csv", 
              colClasses = c("w_geocode" = "character",
                             "h_geocode" = "character"))

full_data16 <- rbind(main, aux)


main15 <- fread("../data/LODES/or_od_main_JT00_2015.csv", 
              colClasses = c("w_geocode" = "character",
                             "h_geocode" = "character"))

aux15 <- fread("../data/LODES/or_od_aux_JT00_2015.csv", 
              colClasses = c("w_geocode" = "character",
                             "h_geocode" = "character"))

full_data15 <- rbind(main, aux)
```

Filtering so that it only includes Wasco County (need to address S. Wasco part)
```{r}
wasco17 <- full_data17 %>% 
  filter(w_geocode %in% full_data17$w_geocode[substr(full_data17$w_geocode, 1, 5) == "41065"]|h_geocode %in% full_data17$h_geocode[substr(full_data17$h_geocode, 1, 5) == "41065"])


wasco16 <- full_data16 %>% 
  filter(w_geocode %in% full_data16$w_geocode[substr(full_data16$w_geocode, 1, 5) == "41065"]|h_geocode %in% full_data16$h_geocode[substr(full_data16$h_geocode, 1, 5) == "41065"])

wasco15 <- full_data15 %>% 
  filter(w_geocode %in% full_data15$w_geocode[substr(full_data15$w_geocode, 1, 5) == "41065"]|h_geocode %in% full_data15$h_geocode[substr(full_data15$h_geocode, 1, 5) == "41065"])
```

```{r}
# select tracts from geocode strings

wasco17$w_geocode_tract <- substr(wasco17$w_geocode, start = 1, stop = 11)
wasco17$h_geocode_tract <- substr(wasco17$h_geocode, start = 1, stop = 11)

wasco16$w_geocode_tract <- substr(wasco16$w_geocode, start = 1, stop = 11)
wasco16$h_geocode_tract <- substr(wasco16$h_geocode, start = 1, stop = 11)

wasco15$w_geocode_tract <- substr(wasco15$w_geocode, start = 1, stop = 11)
wasco15$h_geocode_tract <- substr(wasco15$h_geocode, start = 1, stop = 11)

# aggregate by tract level

jobs_all_2017 <- wasco17 %>% select(-w_geocode, -h_geocode) %>%
  group_by(createdate, w_geocode_tract, h_geocode_tract) %>% 
  summarise(S000 = sum(S000), 
            SA01 = sum(SA01), 
            SA02 = sum(SA02), 
            SA03 = sum(SA03), 
            SE01 = sum(SE01), 
            SE02 = sum(SE02), 
            SE03 = sum(SE03), 
            SI01 = sum(SI01), 
            SI02 = sum(SI02), 
            SI03 = sum(SI03))

jobs_all_2016 <- wasco16 %>% select(-w_geocode, -h_geocode) %>%
  group_by(createdate, w_geocode_tract, h_geocode_tract) %>% 
  summarise(S000 = sum(S000), 
            SA01 = sum(SA01), 
            SA02 = sum(SA02), 
            SA03 = sum(SA03), 
            SE01 = sum(SE01), 
            SE02 = sum(SE02), 
            SE03 = sum(SE03), 
            SI01 = sum(SI01), 
            SI02 = sum(SI02), 
            SI03 = sum(SI03))

jobs_all_2015 <- wasco15 %>% select(-w_geocode, -h_geocode) %>%
  group_by(createdate, w_geocode_tract, h_geocode_tract) %>% 
  summarise(S000 = sum(S000), 
            SA01 = sum(SA01), 
            SA02 = sum(SA02), 
            SA03 = sum(SA03), 
            SE01 = sum(SE01), 
            SE02 = sum(SE02), 
            SE03 = sum(SE03), 
            SI01 = sum(SI01), 
            SI02 = sum(SI02), 
            SI03 = sum(SI03))
```

