---
title: "Visualize ACS Data with Leaflet"
author: "Owen Hart"
date: "7/31/2020"
output: html_document
---

```{r}
library(tidycensus)
library(tidyverse)
library(forcats)
library(data.table)
library(ggplot2)
library(plotly)
library(sf)
library(ggthemes)
library(maps)
library(tigris)
library(here)
library(viridis)
library(dplyr)
library(leaflet)
```

```{r}
#read in combined dataset
acs_data <- fread(here("/data/acs/combined_acs.csv")) 
acs_data$GEOID <- as.character(acs_data$GEOID)
acs_counties <- filter(acs_data, NAME == "South Wasco County School District 1, Oregon" | 
                         NAME == "Wasco County, Oregon"| NAME == "Hood River County, Oregon" |
                         NAME == "Sherman County, Oregon" | NAME == "Jefferson County, Oregon" |
                         NAME == "Multnomah County, Oregon" | NAME == "Clackamas County, Oregon" |
                         NAME == "Marion County, Oregon" | NAME == "Washington County, Oregon" |
                         NAME == "Deschutes County, Oregon" | NAME == "Lane County, Oregon" | 
                         NAME == "Umatilla County, Oregon" |
                         NAME == "Skamania County, Washington" | NAME == "Klickitat County, Washington" | 
                         NAME == "Oregon")  
acs_counties_neighbors <- filter(acs_data, NAME == "South Wasco County School District 1, Oregon" | 
                         NAME == "Wasco County, Oregon"| NAME == "Hood River County, Oregon" |
                         NAME == "Sherman County, Oregon" | NAME == "Jefferson County, Oregon" |
                         NAME == "Skamania County, Washington" |
                         NAME == "Klickitat County, Washington" | NAME == "Oregon")  
#get tract level geography
or_tracts <- tracts(state = "OR", county = c("Wasco", "Hood River", "Sherman", "Jefferson"),
                       cb = TRUE)
wa_tracts <- tracts(state = "WA", county = c("Skamania", "Klickitat"),
                    cb = TRUE)
tract_geo <- rbind(or_tracts, wa_tracts)
acs_tracts <- acs_data %>% filter(grepl("Tract",NAME)) 
acs_tracts <- st_as_sf(inner_join(acs_tracts, tract_geo, by = c("GEOID")))
acs_tracts$NAME <- acs_tracts$NAME.x
acs_tracts$NAME.x <- NULL
acs_tracts$NAME.y <- NULL
#acs_tracts <- geo_join(tract_geo, acs_tracts, by = "GEOID")  
######## USE THE FOLLOWING ##########
# color palette from : https://coolors.co/232d4b-2c4f6b-0e879c-60999a-d1e0bf-d9e12b-e6ce3a-e6a01d-e57200-fdfdfd
graypal = "#ADB5BD"
```
```{r}
or_county_lines <- counties(state = "OR")
wa_county_lines <- counties(state = "WA")
county_lines <- rbind(filter(or_county_lines, NAME %in% 
                               c("Wasco", "Hood River", "Sherman", "Jefferson")),
                      filter(wa_county_lines, NAME %in% c("Skamania", "Klickitat"))
                      )
south_wasco_points <- st_read("../data/shps/swsd")
```

Leaflet of % below poverty line
```{r}
perc_pov_pal <- colorQuantile(viridis_pal(option = "D")(3), domain = acs_tracts$below_poverty)
perc_pov_leaf <- leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolygons(
    data = filter(acs_tracts, year == 2018),
    weight = 1,
    opacity = 0,
    fillOpacity = .7,
    group = "2018",
    fillColor = ~perc_pov_pal(below_poverty),
    label = ~below_poverty) %>%
  addPolygons(
    data = filter(acs_tracts, year == 2017),
    weight = 1,
    opacity = 0,
    fillOpacity = .7,
    group = "2017",
    fillColor = ~perc_pov_pal(below_poverty),
    label = ~below_poverty) %>%
  addPolygons(
    data = filter(acs_tracts, year == 2016),
    weight = 1,
    opacity = 0,
    fillOpacity = .7,
    group = "2016",
    fillColor = ~perc_pov_pal(below_poverty),
    label = ~below_poverty) %>%
  addPolygons(
    data = filter(acs_tracts, year == 2015),
    weight = 1,
    opacity = 0,
    fillOpacity = .7,
    group = "2015",
    fillColor = ~perc_pov_pal(below_poverty),
    label = ~below_poverty) %>%
  addPolylines(
    data = south_wasco_points,
    color = "#5e4b6b",
    weight = 2,
    opacity = 1,
    fillOpacity= 0,
    group = "Basemap",
    label = "South Wasco County Region") %>%
  addPolylines(
    data = county_lines,
    color = "#8d9fcc",
    weight = 2,
    opacity = 1,
    fillOpacity= 0,
    group = "Basemap",
    label = county_lines$NAME) %>%
  addLegend(
    data = acs_tracts,
    "bottomright",
    pal = perc_pov_pal,
    values = ~ below_poverty,
    labFormat = function(type, cuts, p) {
      n = length(cuts)
      p = paste0(round(p * 100), '%')
      cuts = paste0(formatC(cuts[-n]), " - ", formatC(cuts[-1]))},
    title = "Percent of Population below<br>Poverty Line by Census Tract",
    na.label = "NA") %>%
  addLayersControl(
    baseGroups = c("2018", "2017", "2016", "2015"),
    options = layersControlOptions(collapsed = FALSE))
```

Leaflet showing % of employed adults 20-64
```{r}
perc_emp_pal <- colorQuantile(viridis_pal(option = "D")(3), domain = acs_tracts$employment_20_to_64)
perc_emp_leaf <- leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolygons(
    data = filter(acs_tracts, year == 2018),
    weight = 1,
    opacity = 0,
    fillOpacity = .7,
    group = "2018",
    fillColor = ~perc_emp_pal(employment_20_to_64),
    label = ~employment_20_to_64) %>%
  addPolygons(
    data = filter(acs_tracts, year == 2017),
    weight = 1,
    opacity = 0,
    fillOpacity = .7,
    group = "2017",
    fillColor = ~perc_emp_pal(employment_20_to_64),
    label = ~employment_20_to_64) %>%
  addPolygons(
    data = filter(acs_tracts, year == 2016),
    weight = 1,
    opacity = 0,
    fillOpacity = .7,
    group = "2016",
    fillColor = ~perc_emp_pal(employment_20_to_64),
    label = ~employment_20_to_64) %>%
  addPolygons(
    data = filter(acs_tracts, year == 2015),
    weight = 1,
    opacity = 0,
    fillOpacity = .7,
    group = "2015",
    fillColor = ~perc_emp_pal(employment_20_to_64),
    label = ~employment_20_to_64) %>%
  addPolylines(
    data = south_wasco_points,
    color = "#5e4b6b",
    weight = 2,
    opacity = 1,
    fillOpacity= 0,
    group = "Basemap",
    label = "South Wasco County Region") %>%
  addPolylines(
    data = county_lines,
    color = "#8d9fcc",
    weight = 2,
    opacity = 1,
    fillOpacity= 0,
    group = "Basemap",
    label = county_lines$NAME) %>%
  addLegend(
    data = acs_tracts,
    "bottomright",
    pal = perc_emp_pal,
    values = ~ employment_20_to_64,
    labFormat = function(type, cuts, p) {
      n = length(cuts)
      p = paste0(round(p * 100), '%')
      cuts = paste0(formatC(cuts[-n]), " - ", formatC(cuts[-1]))},
    title = "Percent of Employed Adults<br>20 to 64 by Census Tract",
    na.label = "NA") %>%
  addLayersControl(
    baseGroups = c("2018", "2017", "2016", "2015"),
    options = layersControlOptions(collapsed = FALSE))
```

categories now!
(Income Distribution, Educational Attainment, Racial and Ethnic Diversity, and Family Stability.)

```{r}
#grouped bar charts
income <- dplyr::select(filter(acs_counties, year == 2018), NAME, contains("income"))
income <- income %>% dplyr::select(!contains("moe"), -median_household_income)
income <- melt(income, id.vars = "NAME", measure.vars = colnames(income)[-1])
ggplotly(ggplot(income)+
  geom_col(aes(x = NAME, y = value, fill = variable), position = "dodge")+ 
    scale_fill_manual(values = viridis(10, option = "D")) +
  # scale_fill_discrete(name = "Income Bracket", labels = c("Less than 10,000", "10,000-14,999", "15,000-24,999",
  #                                                         "25,000-34,999", "35,000-49,999", "50,000-74,999", 
  #                                                         "75,000-99,999","100,000-149,999", "150,000-199,999", "above 200,000")) +
  #scale_colour_manual(name = "Income Bracket", values = dspgpal) +
  #theme_minimal()+theme(axis.text.x = element_text(angle=30)) +
  ylab("% of Population") + xlab("Region") +
  ggtitle("Income Distribution for 2018") + coord_flip())

```

```{r}
income_dist <- dplyr::select(filter(acs_tracts), NAME, year, contains("income"), geometry)%>% dplyr::select(!contains("moe"), -median_household_income)
income_dist_2018 <- filter(income_dist, year == 2018)
income_dist_2017 <- filter(income_dist, year == 2017)
income_dist_2016 <- filter(income_dist, year == 2016)
income_dist_2015 <- filter(income_dist, year == 2015)
income_dist_2018
```

leaflet income dist 2018
```{r}
income_dist_18_pal <- colorNumeric(viridis_pal(option = "D")(3), domain = c(0, 28.40))

income_dist_2018_leaf <- leaflet(income_dist_2018) %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolygons(
    weight = 1,
    opacity = 0,
    fillOpacity = .7,
    group = "< $10K",
    fillColor = ~income_dist_18_pal(income_less_than_10k),
    label = ~income_less_than_10k) %>%
  addPolygons(
    weight = 1,
    opacity = 0,
    fillOpacity = .7,
    group = "$10K - $14999",
    fillColor = ~income_dist_18_pal(income_10k_14999),
    label = ~income_10k_14999) %>%
  addPolygons(
    weight = 1,
    opacity = 0,
    fillOpacity = .7,
    group = "$15K - $24999",
    fillColor = ~income_dist_18_pal(income_15k_24999),
    label = ~income_15k_24999) %>%
  addPolygons(
    weight = 1,
    opacity = 0,
    fillOpacity = .7,
    group = "$25K - $34999",
    fillColor = ~income_dist_18_pal(income_25k_34999),
    label = ~income_25k_34999) %>%
  addPolygons(
    weight = 1,
    opacity = 0,
    fillOpacity = .7,
    group = "$35K - $49999",
    fillColor = ~income_dist_18_pal(income_35K_49999),
    label = ~income_35K_49999) %>%
  addPolygons(
    weight = 1,
    opacity = 0,
    fillOpacity = .7,
    group = "$50K - $74999",
    fillColor = ~income_dist_18_pal(income_50K_74999),
    label = ~income_50K_74999) %>%
  addPolygons(
    weight = 1,
    opacity = 0,
    fillOpacity = .7,
    group = "$75K - $99999",
    fillColor = ~income_dist_18_pal(income_75K_99999),
    label = ~income_75K_99999) %>%
  addPolygons(
    weight = 1,
    opacity = 0,
    fillOpacity = .7,
    group = "$100K - $149999",
    fillColor = ~income_dist_18_pal(income_100K_149999),
    label = ~income_100K_149999) %>%
  addPolygons(
    weight = 1,
    opacity = 0,
    fillOpacity = .7,
    group = "$150K - $199999",
    fillColor = ~income_dist_18_pal(income_150K_199999),
    label = ~income_150K_199999) %>%
  addPolygons(
    weight = 1,
    opacity = 0,
    fillOpacity = .7,
    group = "> $200K",
    fillColor = ~income_dist_18_pal(income_200K_more),
    label = ~income_200K_more) %>%
  addPolylines(
    data = south_wasco_points,
    color = "#ffce9e",
    weight = 2,
    opacity = 1,
    fillOpacity= 0,
    group = "Basemap",
    label = "South Wasco County Region") %>%
  addPolylines(
    data = county_lines,
    color = "#d48537",
    weight = 2,
    opacity = 1,
    fillOpacity= 0,
    group = "Basemap",
    label = county_lines$NAME) %>%
  addLegend(
    "bottomright",
    pal = income_dist_18_pal,
    values = ~ c(0, 28.40),
    title = "% of Population in selected<br>Income Bracket by Census Tract (2018)",
    na.label = "NA") %>%
  addLayersControl(
    baseGroups = c("< $10K", "$15K - $24999", "$25K - $34999", "$35K - $49999",
                   "$50K - $74999", "$75K - $99999","$100K - $149999", "$150K - $199999",
                   "> $200K"),
    options = layersControlOptions(collapsed = T))
```

leaflet income dist 2017
```{r}
income_dist_17_pal <- colorNumeric(viridis_pal(option = "D")(3), domain = c(0, 31.60))
income_dist_2017_leaf <- leaflet(income_dist_2017) %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolygons(
    weight = 1,
    opacity = 0,
    fillOpacity = .7,
    group = "< $10K",
    fillColor = ~income_dist_17_pal(income_less_than_10k),
    label = ~income_less_than_10k) %>%
  addPolygons(
    weight = 1,
    opacity = 0,
    fillOpacity = .7,
    group = "$10K - $14999",
    fillColor = ~income_dist_17_pal(income_10k_14999),
    label = ~income_10k_14999) %>%
  addPolygons(
    weight = 1,
    opacity = 0,
    fillOpacity = .7,
    group = "$15K - $24999",
    fillColor = ~income_dist_17_pal(income_15k_24999),
    label = ~income_15k_24999) %>%
  addPolygons(
    weight = 1,
    opacity = 0,
    fillOpacity = .7,
    group = "$25K - $34999",
    fillColor = ~income_dist_17_pal(income_25k_34999),
    label = ~income_25k_34999) %>%
  addPolygons(
    weight = 1,
    opacity = 0,
    fillOpacity = .7,
    group = "$35K - $49999",
    fillColor = ~income_dist_17_pal(income_35K_49999),
    label = ~income_35K_49999) %>%
  addPolygons(
    weight = 1,
    opacity = 0,
    fillOpacity = .7,
    group = "$50K - $74999",
    fillColor = ~income_dist_17_pal(income_50K_74999),
    label = ~income_50K_74999) %>%
  addPolygons(
    weight = 1,
    opacity = 0,
    fillOpacity = .7,
    group = "$75K - $99999",
    fillColor = ~income_dist_17_pal(income_75K_99999),
    label = ~income_75K_99999) %>%
  addPolygons(
    weight = 1,
    opacity = 0,
    fillOpacity = .7,
    group = "$100K - $149999",
    fillColor = ~income_dist_17_pal(income_100K_149999),
    label = ~income_100K_149999) %>%
  addPolygons(
    weight = 1,
    opacity = 0,
    fillOpacity = .7,
    group = "$150K - $199999",
    fillColor = ~income_dist_17_pal(income_150K_199999),
    label = ~income_150K_199999) %>%
  addPolygons(
    weight = 1,
    opacity = 0,
    fillOpacity = .7,
    group = "> $200K",
    fillColor = ~income_dist_17_pal(income_200K_more),
    label = ~income_200K_more) %>%
  addPolylines(
    data = south_wasco_points,
    color = "#ffce9e",
    weight = 2,
    opacity = 1,
    fillOpacity= 0,
    group = "Basemap",
    label = "South Wasco County Region") %>%
  addPolylines(
    data = county_lines,
    color = "#d48537",
    weight = 1,
    opacity = 1,
    fillOpacity= 0,
    group = "Basemap",
    label = county_lines$NAME) %>%
  addLegend(
    "bottomright",
    pal = income_dist_17_pal,
    values = ~ c(0, 31.60),
    title = "% of Population in selected<br>Income Bracket by Census Tract (2017)",
    na.label = "NA") %>%
  
  addLayersControl(
    baseGroups = c("< $10K", "$15K - $24999", "$25K - $34999", "$35K - $49999",
                   "$50K - $74999", "$75K - $99999","$100K - $149999", "$150K - $199999",
                   "> $200K"),
    options = layersControlOptions(collapsed = T))
```

leaflet income dist 2016
```{r}
income_dist_16_pal <- colorNumeric(viridis_pal(option = "D")(3), domain = c(0, 27.60))
income_dist_2016_leaf <- leaflet(income_dist_2016) %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolygons(
    weight = 1,
    opacity = 0,
    fillOpacity = .7,
    group = "< $10K",
    fillColor = ~income_dist_16_pal(income_less_than_10k),
    label = ~income_less_than_10k) %>%
  addPolygons(
    weight = 1,
    opacity = 0,
    fillOpacity = .7,
    group = "$10K - $14999",
    fillColor = ~income_dist_16_pal(income_10k_14999),
    label = ~income_10k_14999) %>%
  addPolygons(
    weight = 1,
    opacity = 0,
    fillOpacity = .7,
    group = "$15K - $24999",
    fillColor = ~income_dist_16_pal(income_15k_24999),
    label = ~income_15k_24999) %>%
  addPolygons(
    weight = 1,
    opacity = 0,
    fillOpacity = .7,
    group = "$25K - $34999",
    fillColor = ~income_dist_16_pal(income_25k_34999),
    label = ~income_25k_34999) %>%
  addPolygons(
    weight = 1,
    opacity = 0,
    fillOpacity = .7,
    group = "$35K - $49999",
    fillColor = ~income_dist_16_pal(income_35K_49999),
    label = ~income_35K_49999) %>%
  addPolygons(
    weight = 1,
    opacity = 0,
    fillOpacity = .7,
    group = "$50K - $74999",
    fillColor = ~income_dist_16_pal(income_50K_74999),
    label = ~income_50K_74999) %>%
  addPolygons(
    weight = 1,
    opacity = 0,
    fillOpacity = .7,
    group = "$75K - $99999",
    fillColor = ~income_dist_16_pal(income_75K_99999),
    label = ~income_75K_99999) %>%
  addPolygons(
    weight = 1,
    opacity = 0,
    fillOpacity = .7,
    group = "$100K - $149999",
    fillColor = ~income_dist_16_pal(income_100K_149999),
    label = ~income_100K_149999) %>%
  addPolygons(
    weight = 1,
    opacity = 0,
    fillOpacity = .7,
    group = "$150K - $199999",
    fillColor = ~income_dist_16_pal(income_150K_199999),
    label = ~income_150K_199999) %>%
  addPolygons(
    weight = 1,
    opacity = 0,
    fillOpacity = .7,
    group = "> $200K",
    fillColor = ~income_dist_16_pal(income_200K_more),
    label = ~income_200K_more) %>%
  addPolylines(
    data = south_wasco_points,
    color = "#ffce9e",
    weight = 2,
    opacity = 1,
    fillOpacity= 0,
    group = "Basemap",
    label = "South Wasco County Region") %>%
  addPolylines(
    data = county_lines,
    color = "#d48537",
    weight = 1,
    opacity = 1,
    fillOpacity= 0,
    group = "Basemap",
    label = county_lines$NAME) %>%
  addLegend(
    "bottomright",
    pal = income_dist_16_pal,
    values = ~ c(0, 27.60),
    title = "% of Population in selected<br>Income Bracket by Census Tract (2016)",
    na.label = "NA") %>%
  addLayersControl(
    baseGroups = c("< $10K", "$15K - $24999", "$25K - $34999", "$35K - $49999",
                   "$50K - $74999", "$75K - $99999","$100K - $149999", "$150K - $199999",
                   "> $200K"),
    options = layersControlOptions(collapsed = T))
```

leaflet income dist 2015
```{r}
income_dist_15_pal <- colorNumeric(viridis_pal(option = "D")(3), domain = c(0, 32.900))
income_dist_2015_leaf <- leaflet(income_dist_2015) %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolygons(
    weight = 1,
    opacity = 0,
    fillOpacity = .7,
    group = "< $10K",
    fillColor = ~income_dist_15_pal(income_less_than_10k),
    label = ~income_less_than_10k) %>%
  addPolygons(
    weight = 1,
    opacity = 0,
    fillOpacity = .7,
    group = "$10K - $14999",
    fillColor = ~income_dist_15_pal(income_10k_14999),
    label = ~income_10k_14999) %>%
  addPolygons(
    weight = 1,
    opacity = 0,
    fillOpacity = .7,
    group = "$15K - $24999",
    fillColor = ~income_dist_15_pal(income_15k_24999),
    label = ~income_15k_24999) %>%
  addPolygons(
    weight = 1,
    opacity = 0,
    fillOpacity = .7,
    group = "$25K - $34999",
    fillColor = ~income_dist_15_pal(income_25k_34999),
    label = ~income_25k_34999) %>%
  addPolygons(
    weight = 1,
    opacity = 0,
    fillOpacity = .7,
    group = "$35K - $49999",
    fillColor = ~income_dist_15_pal(income_35K_49999),
    label = ~income_35K_49999) %>%
  addPolygons(
    weight = 1,
    opacity = 0,
    fillOpacity = .7,
    group = "$50K - $74999",
    fillColor = ~income_dist_15_pal(income_50K_74999),
    label = ~income_50K_74999) %>%
  addPolygons(
    weight = 1,
    opacity = 0,
    fillOpacity = .7,
    group = "$75K - $99999",
    fillColor = ~income_dist_15_pal(income_75K_99999),
    label = ~income_75K_99999) %>%
  addPolygons(
    weight = 1,
    opacity = 0,
    fillOpacity = .7,
    group = "$100K - $149999",
    fillColor = ~income_dist_16_pal(income_100K_149999),
    label = ~income_100K_149999) %>%
  addPolygons(
    weight = 1,
    opacity = 0,
    fillOpacity = .7,
    group = "$150K - $199999",
    fillColor = ~income_dist_15_pal(income_150K_199999),
    label = ~income_150K_199999) %>%
  addPolygons(
    weight = 1,
    opacity = 0,
    fillOpacity = .7,
    group = "> $200K",
    fillColor = ~income_dist_15_pal(income_200K_more),
    label = ~income_200K_more) %>%
  addPolylines(
    data = south_wasco_points,
    color = "#ffce9e",
    weight = 2,
    opacity = 1,
    fillOpacity= 0,
    group = "Basemap",
    label = "South Wasco County Region") %>%
  addPolylines(
    data = county_lines,
    color = "#d48537",
    weight = 1,
    opacity = 1,
    fillOpacity= 0,
    group = "Basemap",
    label = county_lines$NAME) %>%
  addLegend(
    "bottomright",
    pal = income_dist_15_pal,
    values = ~ c(0, 32.900),
    title = "% of Population in selected<br>Income Bracket by Census Tract (2015)",
    na.label = "NA") %>%
  addLayersControl(
    baseGroups = c("< $10K", "$15K - $24999", "$25K - $34999", "$35K - $49999",
                   "$50K - $74999", "$75K - $99999","$100K - $149999", "$150K - $199999",
                   "> $200K"),
    options = layersControlOptions(collapsed = T))
```


