---
title: "Water Use Data"
author: "Owen Hart"
date: "7/29/2020"
output: html_document
---

```{r}
library(R.utils)
library(data.table)
library(tidyr)
library(dplyr)
library(readr)
library(ggplot2)
library(sf)
library(leaflet)
library(mapview)
library(reshape2)
library(raster)
library(tigris)
```

Loading in water use data
```{r}
url <- "https://waterdata.usgs.gov/or/nwis/water_use?format=rdb&rdb_compression=value&wu_area=County&wu_year=ALL&wu_county=065&wu_category=TP%2CPS%2CDO%2CCO%2CIN%2CMI%2CLI%2CLS%2CLA%2CAQ%2CIC%2CWW&wu_county_nms=Wasco%2BCounty&wu_category_nms=Total%2BPopulation%252CPublic%2BSupply%252CDomestic%252CCommercial%252CIndustrial%252CMining%252CLivestock%252CLivestock%2BStock%252CLivestock%2BAnimal%2BSpecialties%252CAquaculture%252CIrrigation%252C%2BCrop%252CWastewater%2BTreatment"

df <- read.table(url, sep = '\t',header = T)
df <- df[-1, ]
df
```


Collapsing rows
```{r}
x <- data.frame(t(df[, -5]))
colnames(x) <- df$year

x$var <- colnames(df)[-5]
x[(x$var %like% "Public") & (x$var %like% "Mgal.d"), ]$var <- "Total Water supplied to Public (mGal/D)"
x[(x$var %like% "Domestic") & (x$var %like% "Mgal.d"),]$var <- "Domestic Water Use (mGal/D)"
x[(x$var %like% "Commercial") & (x$var %like% "Mgal.d"),]$var <- "Commercial Water Use (mGal/D)"
x[(x$var %like% "Industrial") & (x$var %like% "Mgal.d"),]$var <- "Industrial Water Use (mGal/D)"
x[(x$var %like% "Mining") & (x$var %like% "Mgal.d"), ]$var <- "Mining Water Use (mGal/D)"
x[(x$var %like% "Livestock") & (x$var %like% "Mgal.d"), ]$var <- "Livestock Water Use (mGal/D)"
x[(x$var %like% "Aquaculture") & (x$var %like% "Mgal.d"), ]$var <- "Aquaculture Water Use (mGal/D)"
x[(x$var %like% "Wastewater") & (x$var %like% "Mgal.d"), ]$var <- "Waster Treatment (mGal/D)"
x[(x$var %like% "Irrigation") & (x$var %like% "Mgal.d"), ]$var <- "Irrigation Water Use (mGal/D)"

x$`1985`<- as.numeric(x$`1985`)
x$`1990`<- as.numeric(x$`1990`)
x$`1995`<- as.numeric(x$`1995`)
x$`2000`<- as.numeric(x$`2000`)
x$`2005`<- as.numeric(x$`2005`)
x$`2010`<- as.numeric(x$`2010`)
x$`2015`<- as.numeric(x$`2015`)

x[is.na(x)] <- 0
x
```
Aggregating by type
```{r}
water_use_by_sector <- x %>% 
  group_by(var) %>%
  summarise(`1985` = sum(`1985`),
            `1990` = sum(`1990`),
            `1995` = sum(`1995`),
            `2000` = sum(`2000`),
            `2005` = sum(`2005`),
            `2010` = sum(`2010`),
            `2015` = sum(`2015`))
water_use_by_sector <- water_use_by_sector[water_use_by_sector$var %like% "(mGal/D)", ]
water_use_by_sector
```

